version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    environment:
      bar: ${bar}
      foo: ${foo}
    ports:
     - "9080:80"
  mysql:
    image: mysql:5.6
    ports:
     - "13306:3306"
